// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsSwsz1MoQyiDsgKV6e3Vo9_A4bo3xznA',
    appId: '1:18758494878:web:df872a1e89e9f4adfe298f',
    messagingSenderId: '18758494878',
    projectId: 'fitstart-dc5bd',
    authDomain: 'fitstart-dc5bd.firebaseapp.com',
    storageBucket: 'fitstart-dc5bd.firebasestorage.app',
    measurementId: 'G-DGHPCD7CCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjWu8ditP-NzRikuKdHcEl7xqGL1qvRdk',
    appId: '1:18758494878:android:d49fd467faf3eb9afe298f',
    messagingSenderId: '18758494878',
    projectId: 'fitstart-dc5bd',
    storageBucket: 'fitstart-dc5bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_T3afLcaIZDUjB0AlJ6gQo-itOi1qw4E',
    appId: '1:18758494878:ios:27862617ee09fcebfe298f',
    messagingSenderId: '18758494878',
    projectId: 'fitstart-dc5bd',
    storageBucket: 'fitstart-dc5bd.firebasestorage.app',
    iosBundleId: 'com.fitstart.fitstartMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_T3afLcaIZDUjB0AlJ6gQo-itOi1qw4E',
    appId: '1:18758494878:ios:27862617ee09fcebfe298f',
    messagingSenderId: '18758494878',
    projectId: 'fitstart-dc5bd',
    storageBucket: 'fitstart-dc5bd.firebasestorage.app',
    iosBundleId: 'com.fitstart.fitstartMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsSwsz1MoQyiDsgKV6e3Vo9_A4bo3xznA',
    appId: '1:18758494878:web:564038de440b1ae2fe298f',
    messagingSenderId: '18758494878',
    projectId: 'fitstart-dc5bd',
    authDomain: 'fitstart-dc5bd.firebaseapp.com',
    storageBucket: 'fitstart-dc5bd.firebasestorage.app',
    measurementId: 'G-VMVVDD4YW4',
  );
}
